### ISSUE TITLE
Discord linking

### ISSUE THREAD

**Issue by JustAFridg** [dolosarafat/AfkPool#2]
Hi ShackInTheMiddle and dolosarafat,
I know this isn't the right place to tell you this, but I could not find another way to contact you...

So if you go to the [Modrinth page](https://modrinth.com/plugin/afk-pool) and try to click on any of the following buttons (except the source one),
![image](https://github.com/kmaba/AfkPool/assets/123732650/23dd67fe-9c35-46c0-a048-838e26751f78)
you go to https://dsc.gg/vorbullmc. But there is one problem, the link is invalid. This is the same for this
![image](https://github.com/kmaba/AfkPool/assets/123732650/d15861a1-0f83-42b0-861e-44f9bf1de587)
link.

Thanks for this amazing project / plugin and I'll definitely be using it in my server (which I wanted to be added to the 'Servers Currently Using This Plugin', where I needed the Discord invite link for)

**Comment by kmaba** [comment]
Hey, thanks for pointing that out, the test server is down and we are not planning on bringing it back up and the discord link is the remains of an old Minecraft server, I’ll remove the broken links, Thank you for using my plugin ❤️
